californiaspa/Controllers/MainController.cs
using californiaspa.DataBase;
using californiaspa.Models;
using californiaspa.Models.booking;
using californiaspa.utilis;
using System;
using System.Web;
using System.Web.Mvc;

namespace californiaspa.Controllers
{
    public class MainController : Controller
    {
        public ActionResult AboutUs()
        {
            return base.View();
        }

        [AuthorizeVerifiedtherapist]
        public ActionResult ClientSurvey(int _xid, int aid)
        {
            ClientSurveymodel clientSurveymodel = new ClientSurveymodel();
            bookingServices bookingService = new bookingServices();
            if (Convert.ToInt32(Session["thId"].ToString()) == _xid)
            {
                clientSurveymodel = bookingService.CheckCLientPendingSurveryByAId(aid);
                clientSurveymodel.AID = aid;
                if (!clientSurveymodel.pendingServey)
                {
                    clientSurveymodel.ErrorText = string.Concat("Survery already completed for this appointement date :", clientSurveymodel.appointment_date, ";", clientSurveymodel.appointment_time);
                }
            }
            else
            {
                clientSurveymodel.ErrorText = "No Survey exist currently";
            }
            return base.View(clientSurveymodel);
        }
        
        [HttpPost]
        public ActionResult completeClientSurvey(ClientSurveymodel _model)
        {
            if (!new cookiechecker().iscookieexist())
            {
                return base.View("ClientSurvey", _model);
            }
            bookingServices bookingService = new bookingServices();
            smshelper _smshelper = new smshelper();
            string str = bookingService.SaveClientSurvey(_model);
            if (str.Contains("Error"))
            {
                _model.ErrorText = str;
            }
            else
            {
                string[] strArrays = str.Split(new char[] { '-' });
                //string str1 = strArrays.Length>1? string.Concat(string.Concat("CLSPA :", strArrays[1], " completed survey feedback for "), strArrays[0]): "CLSPA : Appointment Id : "+ _model.AID + "  completed survey feedback by therapist" ;
                string str1 = strArrays.Length > 1 ? string.Concat(string.Concat("CAL SPA : ADMIN <br/><br/>", strArrays[1], " completed survey feedback for "), strArrays[0]) : "CAL SPA : ADMIN<br/><br/>  Appointment Id : " + _model.AID + "  completed survey feedback by therapist";
               // _smshelper.SendSms("9591895700", str1, "+14177089506");
                _model.ErrorText = "Thank you for participating in survey , We appreciate your valuable feedback";
            }
            return base.View("ClientSurvey", _model);
        }

        [HttpPost]
        public ActionResult completeSurvey(Surveymodel _model)
        {
            if (!new cookiechecker().iscookieexist())
            {
                return base.View("Survey", _model);
            }
            bookingServices bookingService = new bookingServices();
            smshelper _smshelper = new smshelper();
            string str = bookingService.SaveSurvey(_model);
            if (str.Contains("Error"))
            {
                _model.ErrorText = str;
            }
            else
            {
                string[] strArrays = str.Split(new char[] { '-' });
                string str1 = strArrays.Length > 1 ? string.Concat(string.Concat("CAL SPA : ADMIN <br/>", strArrays[0], " complete survey feedback for "), strArrays[1]) : "CAL SPA : ADMIN<br/> Appointment Id : " + _model.AID + "  completed survey feedback by therapist";
               // _smshelper.SendSms("9591895700", str1, "+14177089506");
                _model.ErrorText = "Thank you for participating in survey , We appreciate your valuable feedback";
            }
            return base.View("Survey", _model);
        }

        [AuthorizeVerifieduser]
        public ActionResult dashboard()
        {
            return base.View();
        }

        public ActionResult FemaleMassage()
        {
            return base.View();
        }

        public PartialViewResult GetClientSurvey(string token)
        {
            if (!new cookiechecker().iscookieexist())
            {
                return base.PartialView("Survey");
            }
            bookingServices bookingService = new bookingServices();
            Crypto crypto = new Crypto();
            int num = 0;
            if (!string.IsNullOrEmpty(token))
            {
                token = token.Replace(" ", "+");
                num = Convert.ToInt32(crypto.DecryptStringAES(token));
            }
            return base.PartialView(bookingService.GetClientSurveyByIdSurvey(num, token));
        }

        public FileResult getId(string name)
        {
            string str = Server.MapPath(string.Concat("~/profileImages/", name));
            string empty = string.Empty;
            if (name.Contains(".pdf"))
            {
                empty = "application/pdf";
            }
            else
            {
                empty = (!name.Contains(".docx") ? "image/jpeg" : "application/docx");
            }
            return this.File(str, empty, name);
        }

        public PartialViewResult GetSurvey(string token, string name = "")
        {
            if (!new cookiechecker().iscookieexist())
            {
                return base.PartialView("Survey");
            }
            bookingServices bookingService = new bookingServices();
            Crypto crypto = new Crypto();
            int num = 0;
            if (!string.IsNullOrEmpty(token))
            {
                token = token.Replace(" ", "+");
                num = Convert.ToInt32(crypto.DecryptStringAES(token));
            }
            Surveymodel terapistSurveyByIdSurvey = bookingService.GetTerapistSurveyByIdSurvey(num, token);
            if (!string.IsNullOrEmpty(name))
            {
                terapistSurveyByIdSurvey.therapistName = name;
            }
            return base.PartialView(terapistSurveyByIdSurvey);
        }

        public ActionResult HomeMassage()
        {
            return base.View();
        }

        public ActionResult Index()
        {
            utility _utility = new utility();
            if (Request.Url.AbsoluteUri.Contains("https") && !base.Request.Url.AbsoluteUri.Contains("localhost"))
            {
                return base.View();
            }
            return this.Redirect("https://www.californiamassage.in/main/index");
            //return View();
        }

        public ActionResult Jobs()
        {
            return base.View();
        }

        public ActionResult MassageStyle()
        {
            return base.View();
        }

        [AuthorizeVerifieduser]
        public ActionResult Survey(int _xid, int aid)
        {
            Surveymodel surveymodel = new Surveymodel();
            bookingServices bookingService = new bookingServices();
            if (Convert.ToInt32(Session["cluserId"].ToString()) == _xid)
            {
                surveymodel = bookingService.CheckPendingSurveryByAId(aid);
                if (!surveymodel.pendingServey)
                {
                    surveymodel.ErrorText = string.Concat("Survery already completed for this appointement date :", surveymodel.appointment_date, ";", surveymodel.appointment_time);
                }
                surveymodel.AID = aid;
            }
            else
            {
                surveymodel.ErrorText = "No Survey exist currently ";
            }
            return base.View(surveymodel);
        }

        public ActionResult Testimonials()
        {
            return base.View();
        }
    }
}

californiaspa/Controllers/TAccountController.cs
using californiaspa.DataBase;
using californiaspa.Models;
using californiaspa.Models.Account;
using californiaspa.Models.Appointment;
using californiaspa.Models.Chat;
using californiaspa.Models.therapist;
using californiaspa.utilis;
using System;
using System.Collections.Specialized;
using System.IO;
using System.Linq;
using System.Net;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace californiaspa.Controllers
{
    public class TAccountController : Controller
    {
        [AuthorizeVerifiedtherapist]
        public ActionResult appointment_reminder(int? deleteId,int? page)
        {
            int thid = Convert.ToInt32(Session["thId"]);
            page = page ?? 1;
            utility _utility = new utility();
            int num = 1;
            int num1 = (page.HasValue ? page.Value : 10);
            decimal one = decimal.One;
            if (page.HasValue)
            {
                num = (Convert.ToInt32(page) - 1) * 10;
                one = Convert.ToInt32(page);
                num++;
            }
            num1 = (Convert.ToInt32(page)) * 10;
            int total = 0;
            ChatServices chatService = new ChatServices();
            NotificationModel notificationModel = new NotificationModel();
            string empty = string.Empty;
            if (deleteId.HasValue)
            {
                empty = chatService.UpdateNotification(deleteId.Value);
            } 
            int? nullable = null;
            notificationModel = chatService.getAllNotifications(num, num1, ref total, nullable, new int?(thid), "", "");
            notificationModel.ErrorText = empty;
            string str = string.Concat(new object[] { "1" });
            HtmlString htmlString = new HtmlString(_utility.create_paging(total, one, "taccount", "appointment_reminder", str, new decimal(10)));
            ViewBag.paging = htmlString;
            return base.View(notificationModel);
        }

        [AuthorizeVerifiedtherapist]
        public ActionResult appointment_request()
        {
            ViewBag.token = Convert.ToInt32(Session["thId"]);
            therapistService _therapistService = new therapistService();
            Schedule schedule = new Schedule();
            schedule.tid = Convert.ToInt32(Session["thId"]);
            string[] strArrays = _therapistService.GetTherapistScheduleId(schedule.tid, false).Split(new char[] { '-' });
            schedule.firstaptTime = strArrays[0];
            schedule.LastaptTime = strArrays[1];
            return base.View(schedule);
        }

        [AuthorizeVerifiedtherapist]
        public ActionResult callschedule(int _xid)
        {
            ViewBag.token = Convert.ToInt32(Session["thId"]);
            therapistService _therapistService = new therapistService();
            Schedule schedule = new Schedule()
            {
                tid = _xid
            };
            string[] strArrays = _therapistService.GetTherapistcallScheduleId(schedule.tid).Split(new char[] { '-' });
            schedule.firstaptTime = strArrays[0];
            schedule.LastaptTime = strArrays[1];
            return base.View(schedule);
        }

        [HttpPost]
        public ActionResult callschedule(Schedule _model)
        {
            ViewBag.token = Convert.ToInt32(Session["thId"]);
            therapistService _therapistService = new therapistService();
            object[] month = new object[5];
            DateTime now = DateTime.Now;
            month[0] = now.Month;
            month[1] = "/";
            now = DateTime.Now;
            month[2] = now.Day;
            month[3] = "/";
            now = DateTime.Now;
            month[4] = now.Year;
            string str = string.Concat(month);
            DateTime dateTime = Convert.ToDateTime(string.Concat(str, " ", _model.firstaptTime));
            if (Convert.ToDateTime(string.Concat(str, " ", _model.LastaptTime)) < dateTime)
            {
                _model.ErrorText = "Latest  time can not grater then Earliest time ";
                return base.View(_model);
            }
            string str1 = _therapistService.UpdateScheduleForcallandmessage(_model.firstaptTime, _model.LastaptTime, _model.tid);
            string[] strArrays = _therapistService.GetTherapistScheduleId(_model.tid, true).Split(new char[] { '-' });
            string[] strArrays1 = _therapistService.GetTherapistcallScheduleId(_model.tid).Split(new char[] { '-' });
            _model.firstaptTime = strArrays[0];
            _model.LastaptTime = strArrays[1];
            _model.callfirstaptTime = strArrays1[0];
            _model.callLastaptTime = strArrays1[1];
            _model.ErrorText = str1;
            return base.View("edit_schedule", _model);
        }

        public void changestatus(bool status, string token)
        {
            if (new cookiechecker().iscookieexist())
            {
                int num = Convert.ToInt32((new Crypto()).DecryptStringAES(token).ToString());
                (new bookingServices()).updateStatusbyThId(num, status);
            }
            
        }

        [AuthorizeVerifiedtherapist]
        public ActionResult Chat(string searchToken = "", int token = 0)
        {
            ViewBag.token = Convert.ToInt32(Session["thId"]);
            ChatServices chatService = new ChatServices();
            Crypto crypto = new Crypto();
            int num = Convert.ToInt32(Session["thId"]);
            TherapistChat therapistChat = new TherapistChat()
            {
                therapistId = num,
                _AdminChatlist = chatService.GetAdminChatByTherapistId(num),
                _TherapistChatlist = chatService.GetAllChatByTherapistId(num, searchToken),
                chatDivId = token
            };
            if (string.IsNullOrEmpty(searchToken))
            {
                return base.View(therapistChat);
            }
            return this.PartialView("SearchChats", therapistChat);
        }

        [AuthorizeVerifiedtherapist]
        public ActionResult ClientAccount(int _xid, int editid)
        {
            ViewBag.token = Convert.ToInt32(Session["thId"]);
            int num = _xid;
            AccountServices accountService = new AccountServices();
            AccountModel accountModel = new AccountModel();
            if (TempData["user"] != null)
            {
                accountModel.ErrorText = TempData["user"].ToString();
            }
            ViewBag.edit = editid;
            accountModel = accountService.GetCustomer(num, true);
            return base.View(accountModel);
        }

        [AuthorizeVerifiedtherapist]
        public ActionResult confirmed_request(string token = "")
        {
            ViewBag.token = Convert.ToInt32(Session["thId"]);
            bookingServices bookingService = new bookingServices();
            int num = Convert.ToInt32(Session["thId"]);
            AppointmentModel confirmedAppointMentDetailByTherapistId = bookingService.GetConfirmedAppointMentDetailByTherapistId(num);
            if (TempData["error"] != null)
            {
                confirmedAppointMentDetailByTherapistId.ErrorText = TempData["error"].ToString();
            }
            return base.View(confirmedAppointMentDetailByTherapistId);
        }

        [HttpPost]
        public string confirmrequest(int id, string res, string lth, string ltd, string time, string confirmDate = "", int clientId = 0, int Aid = 0, string pcktime = "")
        {
            if (!new cookiechecker().iscookieexist())
            {
                return "";
            }
            bookingServices bookingService = new bookingServices();
            therapistService _therapistService = new therapistService();
            
            return bookingService.UpdateConfirmedSTatusByAID(id, res, lth, ltd, time, pcktime);
        }

        [AuthorizeVerifiedtherapist]
        public ActionResult dashboard()
        {
            ViewBag.token = Convert.ToInt32(Session["thId"]);
            return base.View();
        }

        [AuthorizeVerifiedtherapist]
        public ActionResult delete_reminder(string deleteId)
        {
            int num = Convert.ToInt32(Session["thId"]);
            ChatServices chatService = new ChatServices();
            NotificationModel notificationModel = new NotificationModel();
            string empty = string.Empty;
            if (!string.IsNullOrEmpty(deleteId))
            {
                string[] strArrays = deleteId.Split(new char[] { '\u005F' });
                for (int i = 0; i < (int)strArrays.Length; i++)
                {
                    string str = strArrays[i];
                    empty = chatService.UpdateNotification(Convert.ToInt16(str));
                }
            }
            int? nullable = null;
            int total = 0;
            notificationModel = chatService.getAllNotifications(1, 2, ref total, nullable, new int?(num), "", "");
            notificationModel.ErrorText = empty;
            return RedirectToAction("appointment_reminder");

            //return base.View("appointment_reminder", notificationModel);
        }

        [AuthorizeVerifiedtherapist]
        public ActionResult edit_schedule()
        {
            ViewBag.token = Convert.ToInt32(Session["thId"]);
            therapistService _therapistService = new therapistService();
            Schedule schedule = new Schedule()
            {
                tid = Convert.ToInt32(Session["thId"])
            };
            string[] strArrays = _therapistService.GetTherapistScheduleId(schedule.tid, true).Split(new char[] { '-' });
            string[] strArrays1 = _therapistService.GetTherapistcallScheduleId(schedule.tid).Split(new char[] { '-' });
            schedule.firstaptTime = strArrays[0];
            schedule.LastaptTime = strArrays[1];
            schedule.callfirstaptTime = strArrays1[0];
            schedule.callLastaptTime = strArrays1[1];

californiaspa/Views/Main/ClientSurvey.cshtml
@{
    ViewBag.Title = "ClientSurvey";
    Layout = "~/Views/Shared/_LayoutTherapist.cshtml";
}
<style>
input[type=radio], input[type=checkbox] {
    width: 30px !important;
    height: 26px !important;
}
</style>

@model californiaspa.Models.booking.ClientSurveymodel
<div class="row">
    <article class="col-xs-12 maincontent">
        <header class="page-header">
            <h1 class="page-title">
                Therapist Survey for @(!string.IsNullOrEmpty(Model.tname)? Model.tname + " by "+ Model.therapistName +" on Appointment date :"+Model.appointment_date+";"+Model.appointment_time:"")
                <a href="@Url.Action("dashboard","TAccount")" class="btn btn-action pull-right">Return to Therapist home</a>
            </h1>
        </header>
        <div class="col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1">
            <div class="panel panel-default">
                <div class="panel-body">
                    @if (string.IsNullOrEmpty(Model.ErrorText))
                    {
                        using (Html.BeginForm("completeClientSurvey", "Main", FormMethod.Post, new { @id = "frmsendsms" }))
                        {
                            <div class="col-md-7">
                                <div class="top-margin">
                                    @Html.HiddenFor(a => a.token)
                                    <label>Was Clients address location given accurate?</label><br />
                                    @Html.RadioButtonFor(a => a.Q1, "1")<span>Yes</span>
                                    @Html.RadioButtonFor(a => a.Q1, "0")<span>No</span>
                                    @Html.ValidationMessageFor(a => a.Q1)
                                    <br />
                                    @Html.TextBoxFor(a => a.Q1Comment, new { @placeholder = "Additional comments", @class = "form-control" })

                                </div>
                                <div class="top-margin">
                                    <label>Did client delay start of session ?</label><br />
                                    @Html.RadioButtonFor(a => a.Q2, "1")<span>Yes</span>
                                    @Html.RadioButtonFor(a => a.Q2, "0")<span>No</span>
                                    @Html.ValidationMessageFor(a => a.Q2)
                                    <br />
                                    @Html.TextBoxFor(a => a.Q2Comment, new { @placeholder = "Additional comments", @class = "form-control" })
                                </div>
                                <div class="top-margin">
                                    <label>Was Clients House/Apartment reasonably clean?</label><br />
                                    @Html.RadioButtonFor(a => a.Q3, "1")<span>Yes</span>
                                    @Html.RadioButtonFor(a => a.Q3, "0")<span>No</span>
                                    @Html.ValidationMessageFor(a => a.Q3)
                                    <br />
                                    @Html.TextBoxFor(a => a.Q3Comment, new { @placeholder = "Additional comments", @class = "form-control" })
                                </div>
                                <div class="top-margin">
                                    <label>Was Clients neighbourhood safe?</label><br />
                                    @Html.RadioButtonFor(a => a.Q4, "1")<span>Yes</span>
                                    @Html.RadioButtonFor(a => a.Q4, "0")<span>No</span>
                                    @Html.ValidationMessageFor(a => a.Q4)
                                    <br />
                                    @Html.TextBoxFor(a => a.Q4Comment, new { @placeholder = "Additional comments", @class = "form-control" })
                                </div>
                                <div class="top-margin">
                                    <label>Was client polite and respectful?</label><br />
                                    @Html.RadioButtonFor(a => a.Q5, "1")<span>Yes</span>
                                    @Html.RadioButtonFor(a => a.Q5, "0")<span>No</span>
                                    @Html.ValidationMessageFor(a => a.Q5)
                                    <br />
                                    @Html.TextBoxFor(a => a.Q5Comment, new { @placeholder = "Additional comments", @class = "form-control" })
                                </div>
                                <div class="top-margin">
                                    <label>Did client tip you reasonably?</label><br />
                                    @Html.RadioButtonFor(a => a.Q6, "1")<span>Yes</span>
                                    @Html.RadioButtonFor(a => a.Q6, "0")<span>No</span>
                                    @Html.ValidationMessageFor(a => a.Q6)
                                    <br />
                                    @Html.TextBoxFor(a => a.Q6Comment, new { @placeholder = "Additional comments", @class = "form-control" })
                                </div>
                                <div class="top-margin">
                                    <label>Would you like to repeat the client in future?</label><br />
                                    @Html.RadioButtonFor(a => a.Q7, "1")<span>Yes</span>
                                    @Html.RadioButtonFor(a => a.Q7, "0")<span>No</span>
                                    @Html.ValidationMessageFor(a => a.Q7)
                                    <br />
                                    @Html.TextBoxFor(a => a.Q7Comment, new { @placeholder = "Additional comments", @class = "form-control" })
                                </div>
                                <div class="top-margin">
                                    <label>Did he ask for your number or contact info or if you could come direct?</label><br />
                                    @Html.RadioButtonFor(a => a.Q8, "1")<span>Yes</span>
                                    @Html.RadioButtonFor(a => a.Q8, "0")<span>No</span>
                                    @Html.ValidationMessageFor(a => a.Q8)
                                    <br />
                                    @Html.TextBoxFor(a => a.Q8Comment, new { @placeholder = "Additional comments", @class = "form-control" })
                                </div>
                                <div class="top-margin">
                                    <label>Total Score out of 10 : 10 best 1 Worst</label>
                                    @Html.HiddenFor(a => a.AID)
                                    <Select name="rating" class="form-control">
                                        <option>1</option>
                                        <option>2</option>
                                        <option>3</option>
                                        <option>4</option>
                                        <option>5</option>
                                        <option>6</option>
                                        <option>7</option>
                                        <option>8</option>
                                        <option>9</option>
                                        <option>10</option>
                                    </Select>
                                </div>
                                <hr>
                                <div class="row">

                                    <div class="col-lg-9 text-right">
                                        <button class="btn btn-action" type="submit"> Submit Feedback</button>
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                                <div class="row">
                                    <span id="error" class="autohide error"></span>
                                </div>
                            </div>

                        }
                    }
                    else
                    {
                        <span>@Model.ErrorText</span>
                    }
                </div>
            </div>

        </div>

    </article>
    <!-- /Article -->

    <script>
        function AddAlert(message) {
            $(".error").show(1000);
            $("#error").html(message);
           $("#error").animate({ scrollTop: $("#error")[0].scrollHeight }, 1000);
        }


    </script>

</div>

californiaspa/Views/Main/GetClientSurvey.cshtml
@model californiaspa.Models.booking.ClientSurveymodel
@{ var dict = new Dictionary<string, string>
                                                            ();
    dict.Add("True", "Yes");
    dict.Add("False", "No");
}

@helper FormatComment(string Comment)
{
if (!string.IsNullOrEmpty(Comment) && Comment != "N/A")
{
        <span>@Comment</span>
}
else
{
        <span>N/A</span>
}
}
@helper FormatTrueFalse(string Comment)
{
if (Comment.ToUpper() == "FALSE")
{
        <span>No</span>
}
else
{
        <span>Yes</span>
}
}

<link href="@Url.Content("~/assets/css/Booking.css")" rel="stylesheet" />
<div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                Close[&times;]
            </button>
            <h4 class="modal-title">Survey Feedback for @Model.tname by @Model.therapistName</h4>
        </div>
        <div class="modal-body">
            <div class="col-md-7">
                <div class="top-margin">
                    @Html.HiddenFor(a => a.token)
                    <label>Was Clients address location given accurate?</label><br />
                    @FormatTrueFalse(Model.Q1.ToUpper())
                    <br />
                    <label>Comment :</label>@FormatComment(Model.Q1Comment)
                </div>
                <div class="top-margin">
                    <label>Did client delay start of session?</label><br />
                    @FormatTrueFalse(Model.Q2.ToUpper())
                    <br />
                    <label>Comment :</label>@FormatComment(Model.Q2Comment)
                </div>
                <div class="top-margin">
                    <label>Was Clients Location reasonably clean?</label><br />
                    @FormatTrueFalse(Model.Q3.ToUpper())
                    <br />
                    <label>Comment :</label>@FormatComment(Model.Q3Comment)
                </div>
                <div class="top-margin">
                    <label>Was Clients neighbourhood safe?</label><br />
                    @FormatTrueFalse(Model.Q4.ToUpper())
                    <br />
                    <label>Comment :</label>@FormatComment(Model.Q4Comment)
                </div>
            </div>
            <div class="col-md-5">
                <div class="top-margin">
                    <label>Was client polite and respectful?</label><br />
                    @FormatTrueFalse(Model.Q5.ToUpper())
                    <br />
                    <label>Comment :</label>@FormatComment(Model.Q5Comment)
                </div>
                <div class="top-margin">
                    <label>Didi client tip you reasonably?</label><br />
                    @FormatTrueFalse(Model.Q6.ToUpper())
                    <br />
                    <label>Comment :</label>@FormatComment(Model.Q6Comment)
                </div>
                <div class="top-margin">
                    <label>Would you like to repeat the client in future?</label><br />
                    @FormatTrueFalse(Model.Q7.ToUpper())
                    <br />
                    <label>Comment :</label>@FormatComment(Model.Q7Comment)
                </div><div class="top-margin">
    <label>Did he ask for your number or contact info or if you could come direct?</label><br />
    @FormatTrueFalse(Model.Q8.ToUpper())
    <br />
    <label>Comment :</label>@FormatComment(Model.Q8Comment)
</div>
                <div class="top-margin">
                    <label>Total Score out of 10 : 10 best 1 Worst</label><br />
                    <span>@Model.rating</span>
                </div>
            </div>
            <hr>

            <div class="clearfix"></div>
            <div class="row">
                <span id="error" class="autohide error"></span>
            </div>

        </div>

    </div>
    <div class="clearfix"></div>
    <div class="modal-footer">

    </div>

</div>



<script>



    $("input[type=radio]").attr('disabled', true);
    $("input[type=text]").attr('disabled', true);
</script>