californiaspa/Controllers/AdminController.cs
using californiaspa.DataBase;
using californiaspa.Models;
using californiaspa.Models.Account;
using californiaspa.Models.AdminAudio;
using californiaspa.Models.Appointment;
using californiaspa.Models.booking;
using californiaspa.Models.Chat;
using californiaspa.Models.Client;
using californiaspa.Models.therapist;
using californiaspa.Models.user;
using californiaspa.utilis;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace californiaspa.Controllers
{
    public class AdminController : Controller
    {

        [AuthorizeVerifiedAdmin]
        public ActionResult pending_approval_appt(int? page, string tokenid = "")
        {
            page = page ?? 1;
            utility _utility = new utility();
            int num = 1;
            int num1 = (page.HasValue ? page.Value : 10);
            decimal one = decimal.One;
            if (page.HasValue)
            {
                num = (Convert.ToInt32(page) - 1) * 10;
                one = Convert.ToInt32(page);
                num++;
            }
            num1 = (Convert.ToInt32(page)) * 10;
            int total = 0;
            AccountModel accountModel = new AccountModel();
            int userid = (base.Session["ADId"] == null ? 1 : Convert.ToInt32(base.Session["ADId"].ToString()));
            if (!string.IsNullOrEmpty(tokenid))
            {
                var id = Convert.ToInt32(new Crypto().DecryptStringAES(tokenid).ToString());
                bookingServices _bks = new bookingServices();
                _bks.rejectAppointmentRequestonly(id);
                string str1 = Server.UrlEncode("https://www.californiamassage.in/appointment/reject_request?token" + tokenid);
                string str2 = Server.UrlEncode("https://www.californiamassage.in/admin/reject_request?token" + tokenid);
                Task.Factory.StartNew(() => _bks.rejectAppointmentRequestold(id, "Reject Request Approved by Admin at " + DateTime.Now.ToString(), str1, str2));
                accountModel.ErrorText = "Appointment is Canceled";
            }
            AccountServices accountService = new AccountServices();

            if (base.TempData["user"] != null)
            {
                accountModel.ErrorText = base.TempData["user"].ToString();
            }
            accountModel = accountService.GetCustomerpendingapprovalappt(userid, num, num1, ref total);
            string str = string.Concat(new object[] { "1" });
            HtmlString htmlString = new HtmlString(_utility.create_paging(total, one, "admin", "pending_approval_appt", str, new decimal(10)));
            ViewBag.paging = htmlString;
            return base.View(accountModel);
        }


        [AuthorizeVerifiedAdmin]
        public ActionResult approve(int? page)
        {
            page = page ?? 1;
            utility _utility = new utility();
            int num = 1;
            int num1 = (page.HasValue ? page.Value : 10);
            decimal one = decimal.One;
            if (page.HasValue)
            {
                num = (Convert.ToInt32(page) - 1) * 10;
                one = Convert.ToInt32(page);
                num++;
            }
            num1 = (Convert.ToInt32(page)) * 10;
            int total = 0;
            int userid = (base.Session["ADId"] == null ? 1 : Convert.ToInt32(base.Session["ADId"].ToString()));
            AccountServices accountService = new AccountServices();
            AccountModel accountModel = new AccountModel();
            if (base.TempData["user"] != null)
            {
                accountModel.ErrorText = base.TempData["user"].ToString();
            }
            accountModel = accountService.GetCustomerpendingapprovalappt(userid, num, num1, ref total);
            string str = string.Concat(new object[] { "1" });
            HtmlString htmlString = new HtmlString(_utility.create_paging(total, one, "admin", "pending_approval_appt", str, new decimal(10)));
            ViewBag.paging = htmlString;
            return base.View(accountModel);
        }

        [AuthorizeVerifiedAdmin]
        public ActionResult add(int? _xid)
        {
            if (!this.haspermission(16))
            {
                return base.View("acess");
            }
            HotelServices hotelService = new HotelServices();
            spaHotelItem _spaHotelItem = new spaHotelItem();
            _spaHotelItem.type = 1;
            if (_xid.HasValue)
            {
                if (!this.haspermission(18))
                {
                    return base.View("acess");
                }
                _spaHotelItem = hotelService.GetHotelsById(_xid.Value);
                _spaHotelItem.hImages = (
                    from a in hotelService.GetAllHotelsImages()
                    where a.ImgId == _xid.Value
                    select a).ToList<imagesItem>();
            }
            if (base.TempData["msg"] != null)
            {
                _spaHotelItem.ErrorText = base.TempData["msg"].ToString();
            }
            return base.View(_spaHotelItem);
        }

        [AuthorizeVerifiedAdmin]
        public ActionResult addadmin()
        {
            if (!this.haspermission(12))
            {
                return base.View("acess");
            }
            userService _userService = new userService();
            base.ViewBag.roles = _userService.getAllRoles();
            if (base.Session["ADId"] != null)
            {
                Convert.ToInt32(base.Session["ADId"].ToString());
            }
            return base.View(new AdminProfile());
        }

        [HttpPost]
      //  [ValidateAntiForgeryToken]
        public ActionResult addadmin(AdminProfile _model)
        {
            userService _userService = new userService();
           ViewBag.roles = _userService.getAllRoles();
            int num = (base.Session["ADId"] == null ? 1 : Convert.ToInt32(base.Session["ADId"].ToString()));
            Crypto crypto = new Crypto();
            if (_model.confirmPassword != _model.Password)
            {
                _model.ErrorText = "Password and Confirm password must match";
                return base.View(_model);
            }
            string str = (new AdminServices()).CreateAdminXML(_model, num);
            base.TempData["msg"] = str;
            return base.RedirectToAction("user");
        }

        [AuthorizeVerifiedAdmin]
        public ActionResult getotp(int? page, string search = "", int searchtype = -1)
        {
          
            page = page ?? 1;
            utility _utility = new utility();
            int num = 1;
            int num1 = (page.HasValue ? page.Value : 10);
            decimal one = decimal.One;
            if (page.HasValue)
            {
                num = (Convert.ToInt32(page) - 1) * 10;
                one = Convert.ToInt32(page);
                num++;
            }
            num1 = (Convert.ToInt32(page)) * 10;
            int total = 0;
            userService _userService = new userService();
            otpmodel _model = new otpmodel();
            _model = new userService().getotpmodel(num, num1, ref total, search, searchtype);
            string str = string.Concat(new object[] { "1&search=", search, "&searchtype=", searchtype });
            HtmlString htmlString = new HtmlString(_utility.create_paging(total, one, "admin", "getotp", str, new decimal(10)));
            ViewBag.paging = htmlString;
            return View("getotp", _model);
        }


        [AuthorizeVerifiedAdmin]
        public ActionResult appointment_reminder(int? page, string therapistid = "0", string startDate = null, string endDate = null, int? deletId = null)
        {
            if (!this.haspermission(43))
            {
                return base.View("acess");
            }
            page = page ?? 1;
            utility _utility = new utility();
            int num = 1;
            int num1 = (page.HasValue ? page.Value : 10);
            decimal one = decimal.One;
            if (page.HasValue)
            {
                num = (Convert.ToInt32(page) - 1) * 10;
                one = Convert.ToInt32(page);
                num++;
            }
            num1 = (Convert.ToInt32(page)) * 10;
            int total = 0;
            string empty = string.Empty;
            ChatServices chatService = new ChatServices();
            NotificationModel notificationModel = new NotificationModel();
            DropDownServices dropDownService = new DropDownServices();
            if (deletId.HasValue)
            {
                if (!this.haspermission(44))
                {
                    return base.View("acess");
                }
                empty = chatService.UpdateNotification(deletId.Value);
            }
            int? nullable = null;
            notificationModel = chatService.getAllNotifications(num, num1, ref total, nullable, new int?(Convert.ToInt32(therapistid)), startDate, endDate);
            ViewBag.therapist = dropDownService.bindTherapistDropDown(therapistid, 0);
            ViewBag.startDate = (string.IsNullOrEmpty(startDate) ? DateTime.Now.ToString("dd-MMM-y") : startDate);
            ViewBag.endDate = (string.IsNullOrEmpty(endDate) ? DateTime.Now.ToString("dd-MMM-y") : endDate);
            ViewBag.dtchange = (string.IsNullOrEmpty(startDate) ? 0 : 1);
            notificationModel.ErrorText = empty;
            string str = string.Concat(new object[] { "1&therapistid=", therapistid, "&startDate=", startDate, "&endDate=", endDate });
            HtmlString htmlString = new HtmlString(_utility.create_paging(total, one, "admin", "appointment_reminder", str, new decimal(10)));
            ViewBag.paging = htmlString;
            return base.View(notificationModel);
        }

        public void changestatus(string val, int token)
        {

californiaspa/Controllers/MangeController.cs
using californiaspa.DataBase;
using californiaspa.Models.user;
using californiaspa.utilis;
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Mvc;

namespace californiaspa.Controllers
{
    public class MangeController : Controller
    {
        public bool haspermission(int id)
        {
            int num = (Session["ADId"] == null ? 0 : Convert.ToInt32(Session["ADId"]));
            return (new userService()).getPermissionByuserIdd(num).Contains(id);
        }

        [AuthorizeVerifiedAdmin]
        public ActionResult Index(int? roleId)
        {
            if (!this.haspermission(15))
            {
                return base.View("acess");
            }
            
            userService _userService = new userService();
            ViewBag.roles = _userService.getAllRoles();
            RoleModal roleModal1 = new RoleModal();
           int? nullable = roleId;
            roleModal1.roleId = (nullable.HasValue ? nullable.GetValueOrDefault() : 1);
            roleModal1._permissions = _userService.getAllPermissions();
             nullable = roleId;
            ViewBag.rolePermission = _userService.getPermissionByRoleId((nullable.HasValue ? nullable.GetValueOrDefault() : 1));
            return base.View(roleModal1);
        }

        [HttpPost]
        public ActionResult Index(int roleId, int[] chk)
        {
            if (!this.haspermission(15))
            {
                return base.View("acess");
            }
            userService _userService = new userService();
            ViewBag.roles = _userService.getAllRoles();
            RoleModal roleModal = new RoleModal();
            roleModal.roleId = roleId;
            roleModal._permissions = _userService.getAllPermissions();
            roleModal.ErrorText = _userService.updatePermissionByRole(chk, roleId); 
            ViewBag.rolePermission = _userService.getPermissionByRoleId(roleId);
            return base.View(roleModal);
        }
    }
}

californiaspa/Views/Mange/Index.cshtml
@{
    ViewBag.Title = "Role";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
@model californiaspa.Models.user.RoleModal
@{
    int i = 1;
    var roles = (List<californiaspa.Models.user.Roles>)ViewBag.roles;
    var rolepermission = (List<int>)ViewBag.rolePermission;
    var dct = Model._permissions.GroupBy(a => a.type).ToDictionary(a => a.Key, a => a.ToList());
}
<link href="@Url.Content("~/assets/css/Clientprofiles.css")" rel="stylesheet" />
<div class="row">
    <!-- Article main content -->
    <article class="col-xs-12 maincontent">
        <header class="page-header">
            <h3 class="page-title">
                Update Role Permissions
                <a class="btn btn-action pull-right" href="@Url.Action("dashboard","Admin")"> Back to Admin Home</a>
            </h3>
            <div class="clearfix"></div>
            <span class="autohide error">@(!string.IsNullOrEmpty(Model.ErrorText) ? Model.ErrorText : "")</span>
        </header>
        @using (Html.BeginForm("index", "Mange", FormMethod.Post, new { @id = "frmsendsms" }))
        {
         <div class="col-md-12 col-sm-12 ">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="col-md-12 col-sm-12 ">
                        <div class="top-margin">
                            <label>Select Role :</label>
                            <select class="form-control" id="searchBy" name="roleId">
                                @foreach (var item in roles)
                                {
                                    if (item.roleId == Model.roleId)
                                    {
                                        <option selected="selected" value="@item.roleId">@item.name</option>
                                    }
                                    else
                                    {
                                        <option value="@item.roleId">@item.name</option>
                                    }
                                }
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>
            <div class="clearfix"></div>
         <div class="col-md-12 col-sm-12 ">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="row">
                            @foreach (var item in dct)
                            {
                                <div class="col-md-4 col-sm-4">
                                    <h4>@item.Key</h4>
                                    <hr />
                                    @foreach (var items in dct[item.Key])
                                    {
                                        <label>
                                            @if (rolepermission.Contains(items.id))
                                            {
                                                <input checked="checked" type="checkbox" name="chk" value="@items.id" />
                                            }
                                            else
                                            {
                                                <input type="checkbox" name="chk" value="@items.id" />
                                            }
                                            &nbsp; @items.name
                                        </label>
                                        <br />
                                    }
                                </div>
                                i = i + 1;
                                if (i > 3)
                                {
                                    i = 1;
                                    <div class="clearfix"></div>
                                }
                            }
                            <div class="clearfix"></div>
                            <hr />
                        </div>
                        <div class="clearfix"></div>
                        <div class="row text-center">
                            <input type="submit" class="btn btn-action" value="Update Permission" />
                        </div>
                    </div>

                </div>
            </div>
        <div class="clearfix"></div>
        }
    </article>
</div>
<script>
    $("#searchBy").on("change", function () {
        var roleId = $("#searchBy").val();
        location.href = "@Url.Action("index", "Mange")" + "?roleId=" + roleId;
    });
</script>