californiaspa/Models/Chat/AdminChat.cs
using californiaspa.Models;
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;

namespace californiaspa.Models.Chat
{
	public class AdminChat : ErrorModel
	{
		public chatModel _ClientChatlist
		{
			get;
			set;
		}

		public profileList _clientProfiles
		{
			get;
			set;
		}

		public chatModel _ClientTherpistChat
		{
			get;
			set;
		}

		public List<KeywordsSearchProfile> _keywordSearch
		{
			get;
			set;
		}

		public chatModel _TherapistChatlist
		{
			get;
			set;
		}

		public profileList _therapistProfiles
		{
			get;
			set;
		}

		public string ClientsearchToken
		{
			get;
			set;
		}

		public string GLobalsearchToken
		{
			get;
			set;
		}

		public string TherapistsearchToken
		{
			get;
			set;
		}

		public AdminChat()
		{
		}
	}
}

californiaspa/Models/Chat/AdminServeyModel.cs
using californiaspa.Models;
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;

namespace californiaspa.Models.Chat
{
	public class AdminServeyModel : ErrorModel
	{
		public List<SurveyViewModel> _Summarylist
		{
			get;
			set;
		}

		public AdminServeyModel()
		{
		}
	}
}

californiaspa/Models/Chat/AppointementReminder.cs
using System;
using System.Runtime.CompilerServices;

namespace californiaspa.Models.Chat
{
	public class AppointementReminder
	{
		public string _ctoken
		{
			get;
			set;
		}

		public string _ttoken
		{
			get;
			set;
		}

		public string apptCreatedTime
		{
			get;
			set;
		}

		public int ClientId
		{
			get;
			set;
		}

		public string ClientName
		{
			get;
			set;
		}

		public string message
		{
			get;
			set;
		}

		public int MessageId
		{
			get;
			set;
		}

        public int srno
        {
            get;
            set;
        }


        public string sendTime
		{
			get;
			set;
		}

		public int TherapistId
		{
			get;
			set;
		}

		public string TherapistName
		{
			get;
			set;
		}

		public AppointementReminder()
		{
		}
	}
}

californiaspa/Models/Chat/KeywordsSearchProfile.cs
using System;
using System.Runtime.CompilerServices;

namespace californiaspa.Models.Chat
{
	public class KeywordsSearchProfile
	{
		public string Admin
		{
			get;
			set;
		}

		public string client
		{
			get;
			set;
		}

		public int clientId
		{
			get;
			set;
		}

		public string date
		{
			get;
			set;
		}

		public string Message
		{
			get;
			set;
		}

		public int Sender
		{
			get;
			set;
		}

		public string therapist
		{
			get;
			set;
		}

		public int therapistId
		{
			get;
			set;
		}

		public string time
		{
			get;
			set;
		}

		public int total
		{
			get;
			set;
		}

		public KeywordsSearchProfile()
		{
		}
	}
}

californiaspa/Models/Chat/NotificationModel.cs
using californiaspa.Models;
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;

namespace californiaspa.Models.Chat
{
	public class NotificationModel : ErrorModel
	{
		public List<AppointementReminder> _list
		{
			get;
			set;
		}

		public NotificationModel()
		{
		}
	}
}

californiaspa/Models/Chat/SummaryListModel.cs
using californiaspa.Models;
using System;
using System.Runtime.CompilerServices;

namespace californiaspa.Models.Chat
{
	public class SummaryListModel : ErrorModel
	{
		public double Amount
		{
			get;
			set;
		}

		public string Name
		{
			get;
			set;
		}

		public string tokenId
		{
			get;
			set;
		}

		public int Total
		{
			get;
			set;
		}

		public SummaryListModel()
		{
		}
	}
}

californiaspa/Models/Chat/SummaryModel.cs
using californiaspa.Models;
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;

namespace californiaspa.Models.Chat
{
	public class SummaryModel : ErrorModel
	{
		public List<SummaryViewModel> _list
		{
			get;
			set;
		}

		public List<SummaryListModel> _Summarylist
		{
			get;
			set;
		}

		public SummaryModel()
		{
		}
	}
}

californiaspa/Models/Chat/SummaryViewModel.cs
using System;
using System.Runtime.CompilerServices;

namespace californiaspa.Models.Chat
{
	public class SummaryViewModel
	{
		public double Amount
		{
			get;
			set;
		}

		public string bookingDate
		{
			get;
			set;
		}
        public DateTime bookingDate_2 { get; set; }

        public string bookingtime
		{
			get;
			set;
		}

		public int clientId
		{
			get;
			set;
		}

		public string ClientName
		{
			get;
			set;
		}

		public double DiscountAmount
		{
			get;
			set;
		}

		public string Name
		{
			get;
			set;
		}

		public double rate
		{
			get;
			set;
		}

		public int therapistId
		{
			get;
			set;
		}

		public int Total
		{
			get;
			set;
		}

		public string totalamountPerClient
		{
			get;
			set;
		}

		public double totalAmountpertherapist
		{
			get;
			set;
		}

		public int totalMassage
		{
			get;
			set;
		} 
	}
}

californiaspa/Models/Chat/chatModel.cs
using californiaspa.Models;
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;

namespace californiaspa.Models.Chat
{
	public class chatModel : ErrorModel
	{
		public List<sercahChatItem> _chatList
		{
			get;
			set;
		}

		public List<chatModelitem> _list
		{
			get;
			set;
		}

		public chatModel()
		{
		}
	}
}

californiaspa/Controllers/AdminController.cs
using californiaspa.DataBase;
using californiaspa.Models;
using californiaspa.Models.Account;
using californiaspa.Models.AdminAudio;
using californiaspa.Models.Appointment;
using californiaspa.Models.booking;
using californiaspa.Models.Chat;
using californiaspa.Models.Client;
using californiaspa.Models.therapist;
using californiaspa.Models.user;
using californiaspa.utilis;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace californiaspa.Controllers
{
    public class AdminController : Controller
    {

        [AuthorizeVerifiedAdmin]
        public ActionResult pending_approval_appt(int? page, string tokenid = "")
        {
            page = page ?? 1;
            utility _utility = new utility();
            int num = 1;
            int num1 = (page.HasValue ? page.Value : 10);
            decimal one = decimal.One;
            if (page.HasValue)
            {
                num = (Convert.ToInt32(page) - 1) * 10;
                one = Convert.ToInt32(page);
                num++;
            }
            num1 = (Convert.ToInt32(page)) * 10;
            int total = 0;
            AccountModel accountModel = new AccountModel();
            int userid = (base.Session["ADId"] == null ? 1 : Convert.ToInt32(base.Session["ADId"].ToString()));
            if (!string.IsNullOrEmpty(tokenid))
            {
                var id = Convert.ToInt32(new Crypto().DecryptStringAES(tokenid).ToString());
                bookingServices _bks = new bookingServices();
                _bks.rejectAppointmentRequestonly(id);
                string str1 = Server.UrlEncode("https://www.californiamassage.in/appointment/reject_request?token" + tokenid);
                string str2 = Server.UrlEncode("https://www.californiamassage.in/admin/reject_request?token" + tokenid);
                Task.Factory.StartNew(() => _bks.rejectAppointmentRequestold(id, "Reject Request Approved by Admin at " + DateTime.Now.ToString(), str1, str2));
                accountModel.ErrorText = "Appointment is Canceled";
            }
            AccountServices accountService = new AccountServices();

            if (base.TempData["user"] != null)
            {
                accountModel.ErrorText = base.TempData["user"].ToString();
            }
            accountModel = accountService.GetCustomerpendingapprovalappt(userid, num, num1, ref total);
            string str = string.Concat(new object[] { "1" });
            HtmlString htmlString = new HtmlString(_utility.create_paging(total, one, "admin", "pending_approval_appt", str, new decimal(10)));
            ViewBag.paging = htmlString;
            return base.View(accountModel);
        }


        [AuthorizeVerifiedAdmin]
        public ActionResult approve(int? page)
        {
            page = page ?? 1;
            utility _utility = new utility();
            int num = 1;
            int num1 = (page.HasValue ? page.Value : 10);
            decimal one = decimal.One;
            if (page.HasValue)
            {
                num = (Convert.ToInt32(page) - 1) * 10;
                one = Convert.ToInt32(page);
                num++;
            }
            num1 = (Convert.ToInt32(page)) * 10;
            int total = 0;
            int userid = (base.Session["ADId"] == null ? 1 : Convert.ToInt32(base.Session["ADId"].ToString()));
            AccountServices accountService = new AccountServices();
            AccountModel accountModel = new AccountModel();
            if (base.TempData["user"] != null)
            {
                accountModel.ErrorText = base.TempData["user"].ToString();
            }
            accountModel = accountService.GetCustomerpendingapprovalappt(userid, num, num1, ref total);
            string str = string.Concat(new object[] { "1" });
            HtmlString htmlString = new HtmlString(_utility.create_paging(total, one, "admin", "pending_approval_appt", str, new decimal(10)));
            ViewBag.paging = htmlString;
            return base.View(accountModel);
        }

        [AuthorizeVerifiedAdmin]
        public ActionResult add(int? _xid)
        {
            if (!this.haspermission(16))
            {
                return base.View("acess");
            }
            HotelServices hotelService = new HotelServices();
            spaHotelItem _spaHotelItem = new spaHotelItem();
            _spaHotelItem.type = 1;
            if (_xid.HasValue)
            {
                if (!this.haspermission(18))
                {
                    return base.View("acess");
                }
                _spaHotelItem = hotelService.GetHotelsById(_xid.Value);
                _spaHotelItem.hImages = (
                    from a in hotelService.GetAllHotelsImages()
                    where a.ImgId == _xid.Value
                    select a).ToList<imagesItem>();
            }
            if (base.TempData["msg"] != null)
            {
                _spaHotelItem.ErrorText = base.TempData["msg"].ToString();
            }
            return base.View(_spaHotelItem);
        }

        [AuthorizeVerifiedAdmin]
        public ActionResult addadmin()
        {
            if (!this.haspermission(12))
            {
                return base.View("acess");
            }
            userService _userService = new userService();
            base.ViewBag.roles = _userService.getAllRoles();
            if (base.Session["ADId"] != null)
            {
                Convert.ToInt32(base.Session["ADId"].ToString());
            }
            return base.View(new AdminProfile());
        }

        [HttpPost]
      //  [ValidateAntiForgeryToken]
        public ActionResult addadmin(AdminProfile _model)
        {
            userService _userService = new userService();
           ViewBag.roles = _userService.getAllRoles();
            int num = (base.Session["ADId"] == null ? 1 : Convert.ToInt32(base.Session["ADId"].ToString()));
            Crypto crypto = new Crypto();
            if (_model.confirmPassword != _model.Password)
            {
                _model.ErrorText = "Password and Confirm password must match";
                return base.View(_model);
            }
            string str = (new AdminServices()).CreateAdminXML(_model, num);
            base.TempData["msg"] = str;
            return base.RedirectToAction("user");
        }

        [AuthorizeVerifiedAdmin]
        public ActionResult getotp(int? page, string search = "", int searchtype = -1)
        {
          
            page = page ?? 1;
            utility _utility = new utility();
            int num = 1;
            int num1 = (page.HasValue ? page.Value : 10);
            decimal one = decimal.One;
            if (page.HasValue)
            {
                num = (Convert.ToInt32(page) - 1) * 10;
                one = Convert.ToInt32(page);
                num++;
            }
            num1 = (Convert.ToInt32(page)) * 10;
            int total = 0;
            userService _userService = new userService();
            otpmodel _model = new otpmodel();
            _model = new userService().getotpmodel(num, num1, ref total, search, searchtype);
            string str = string.Concat(new object[] { "1&search=", search, "&searchtype=", searchtype });
            HtmlString htmlString = new HtmlString(_utility.create_paging(total, one, "admin", "getotp", str, new decimal(10)));
            ViewBag.paging = htmlString;
            return View("getotp", _model);
        }


        [AuthorizeVerifiedAdmin]
        public ActionResult appointment_reminder(int? page, string therapistid = "0", string startDate = null, string endDate = null, int? deletId = null)
        {
            if (!this.haspermission(43))
            {
                return base.View("acess");
            }
            page = page ?? 1;
            utility _utility = new utility();
            int num = 1;
            int num1 = (page.HasValue ? page.Value : 10);
            decimal one = decimal.One;
            if (page.HasValue)
            {
                num = (Convert.ToInt32(page) - 1) * 10;
                one = Convert.ToInt32(page);
                num++;
            }
            num1 = (Convert.ToInt32(page)) * 10;
            int total = 0;
            string empty = string.Empty;
            ChatServices chatService = new ChatServices();
            NotificationModel notificationModel = new NotificationModel();
            DropDownServices dropDownService = new DropDownServices();
            if (deletId.HasValue)
            {
                if (!this.haspermission(44))
                {
                    return base.View("acess");
                }
                empty = chatService.UpdateNotification(deletId.Value);
            }
            int? nullable = null;
            notificationModel = chatService.getAllNotifications(num, num1, ref total, nullable, new int?(Convert.ToInt32(therapistid)), startDate, endDate);
            ViewBag.therapist = dropDownService.bindTherapistDropDown(therapistid, 0);
            ViewBag.startDate = (string.IsNullOrEmpty(startDate) ? DateTime.Now.ToString("dd-MMM-y") : startDate);
            ViewBag.endDate = (string.IsNullOrEmpty(endDate) ? DateTime.Now.ToString("dd-MMM-y") : endDate);
            ViewBag.dtchange = (string.IsNullOrEmpty(startDate) ? 0 : 1);
            notificationModel.ErrorText = empty;
            string str = string.Concat(new object[] { "1&therapistid=", therapistid, "&startDate=", startDate, "&endDate=", endDate });
            HtmlString htmlString = new HtmlString(_utility.create_paging(total, one, "admin", "appointment_reminder", str, new decimal(10)));
            ViewBag.paging = htmlString;
            return base.View(notificationModel);
        }

        public void changestatus(string val, int token)
        {

californiaspa/Controllers/therapistController.cs
using californiaspa.DataBase;
using californiaspa.Models;
using californiaspa.Models.therapist;
using californiaspa.utilis;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace californiaspa.Controllers
{
    public class therapistController : Controller
    {

        public ActionResult GetEvents(int thid, string start = null, string end = null, int byClient = 0, int cnt = 0)
        {
            if (!new cookiechecker().iscookieexist())
            {
                return Json("",JsonRequestBehavior.AllowGet);
            }
            DateTime dateTime;
            therapistService _therapistService = new therapistService();
            DateTime dateTime1 = (!string.IsNullOrEmpty(start) ? Convert.ToDateTime(start) : DateTime.Now.GetCurrentTimeByTimeZone("India Standard Time"));
            if (string.IsNullOrEmpty(end))
            {
                DateTime currentTimeByTimeZone = DateTime.Now.GetCurrentTimeByTimeZone("India Standard Time");
                dateTime = currentTimeByTimeZone.AddDays(30);
            }
            else
            {
                dateTime = Convert.ToDateTime(end);
            }
            DateTime dateTime2 = dateTime;
            Events[] array = _therapistService.GetEvents(thid, dateTime1, dateTime2, byClient, cnt).ToArray();
            return base.Json(array, 0);
        }

        [HttpPost]
        public string GetEventsByDate(int thid, string start = null, string end = null, string date = null)
        {
            if (!new cookiechecker().iscookieexist())
            {
                return "";
            }
            return (new therapistService()).GetAvailablityWithAppointmentByDate(thid, start, end, date);
        }

        [HttpPost]
        public string GetEventTimeByDate(int thid, DateTime datetime)
        {
           if(!new cookiechecker().iscookieexist())
            {
                return "";
            }
            return (new therapistService()).GetTherapistScheduleId(thid, datetime.Date, false);
        }

        [AuthorizeVerifieduser]
        public ActionResult Index()
        {
            therapistService _therapistService = new therapistService();
            int userid = Convert.ToInt32(Session["cluserId"]);
            bool isnew= _therapistService.checkServiceTaken(userid);
            _therapist allTherapist = _therapistService.GetAllTherapist(false, !isnew);
            allTherapist.images = _therapistService.GetAllTherapistImages();
            if (TempData["mesg"] != null)
            {
                allTherapist.ErrorText = TempData["mesg"].ToString();
            }
            return base.View(allTherapist);
        }
    }
}

californiaspa/Views/Shared/SearchClientViewSummryReport.cshtml
@model californiaspa.Models.Chat.SummaryModel
@{
    Double total = 0.0;
    int totalm = 0;
}
@helper GetFormatTimeDate(string date, string time)
{
    <span>@(Convert.ToDateTime(date).ToString("d-MMM-y")) ; @time</span>
}
@helper GetFormatDate(string date)
{
    <span>@(Convert.ToDateTime(date).ToString("d-MMM-y")) </span>
}
<style>
    .modal-content {
        background-color: #6e0202 !important;
        width: 100%;
    }

    .close {
        color: white;
    }
</style>
<div class="row">
    <div id="AvailableModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" id="AvailableModalclose1" class="close">Close[&times;]</button>
                    <h4 class="modal-title">Massage summary of <span id="cSpan"></span> with <span id="tSpan"></span> (<span id="sSpan"></span> to <span id="eSpan"></span>)</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="top-margin col-md-12 table-responsive" id="schDiv">
                        </div>
                    </div>
                    <input type="hidden" id="tid" />
                    <input type="hidden" id="cid" />
                </div>
                <div class="clearfix"></div>
                <div class="modal-footer">
                    <button type="button" onclick="ExportToExcel()" class="btn btn-action pull-left">Export to Excel</button>
                    <button type="button" class="btn btn-action pull-right" id="AvailableModalclose2">close</button>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="table-responsive">
    <span class="voiletImp">Scroll right to view all massage </span>
    <table class="table-bordered table1 table dt-responsive" id="formats-table">
        <thead class="backgroundskyblue">
            <tr>
                <th>Client name</th>
                <th>Therapist Name</th>
                <th> Massage per Therapist</th>
                <th>  Amount Per Therapist</th>
                <th>View All massage (@ViewBag.start to @ViewBag.end)</th>
            </tr>
        </thead>
        @if (Model._list.Count() > 0)
            {
            <tbody>
                @foreach (var item in Model._list)
                {
                    total += Convert.ToDouble(item.totalamountPerClient);
                    totalm += item.totalMassage;
                    <tr>
                        <td>@item.ClientName</td>
                        <td>@(item.Name)</td>

                        <td> @item.totalMassage   </td>
                        <td>Rs @item.totalamountPerClient   </td>
                        <td><a onclick="GetSummaryItembyid('@item.clientId','@item.therapistId','@item.ClientName','@item.Name')">click to view maggase with @(item.Name)</a></td>
                    </tr>

                }
            </tbody>
            <tfoot>
                <tr>
                    <td></td>
                    <td> </td>
                    <td><span> Total massage:</span><span> <b>@totalm</b> </span> </td>
                    <td><span> Total amount:</span><span>Rs <b>@total</b> </span>   </td>
                    <td></td>
                </tr>
            </tfoot>
        }
        else
        {
            <tr><td colspan="8">No record found</td></tr>
        }
    </table>
</div>
<script>

    function ExportToExcel() {
        var url = "@Url.Action("GetViewSummaryForExport2", "Admin")";
        var startDate = $("#startdate").val();
        var endDate = $("#enddate").val();
        var cid = $("#cid").val();
        var tid = $("#tid").val();
        url = url + "?print=1&startDate=" + startDate + "&tid=" + tid + "&cid=" + cid + "&enddate=" + endDate;
        location.href = url;
    }
    function GetSummaryItembyid(clientid, therspiatid, cname, tname) {
        var url = "@Url.Action("getsubsummary", "Admin")";
        var startDate = $("#startdate").val();
        var endDate = $("#enddate").val();
        $.post(url, { 'startDate': startDate, 'clientId': clientid, 'enddate': endDate, 'therapistId': therspiatid }, function (data) {
            $("#schDiv").html(data);
            $("#tSpan").html(tname);
            $("#cSpan").html(cname);
            $("#sSpan").html(startDate);
            $("#eSpan").html(endDate);
            $("#cid").val(clientid);
            $("#tid").val(therspiatid);
            $('#AvailableModal').modal({ backdrop: 'static', keyboard: false });
        });


    } $("#AvailableModalclose1").click(function () {
        $('#AvailableModal').modal('hide');
    });
    $("#AvailableModalclose2").click(function () {
        $('#AvailableModal').modal('hide');
    });

</script>

californiaspa/Views/Shared/_Layoutuser.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewBag.Title-California SPA</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="" />
    <meta name="author" content="Umesh kumar" />
    <link href="https://fonts.googleapis.com/css?family=Patrick+Hand:300,400,700" rel="stylesheet" />
    <link rel="shortcut icon" href="@Url.Content("~/assets/images/favicon.ico")" />
    <link rel="stylesheet" media="screen" href="@Url.Content("https://fonts.googleapis.com/css?family=Open+Sans:300,400,700")" />
    <link rel="stylesheet" href="@Url.Content("~/assets/css/bootstrap.min.css")" />
    <link rel="stylesheet" href="@Url.Content("~/assets/css/font-awesome.min.css")" />
    <link rel="stylesheet" href="@Url.Content("~/assets/css/bootstrap-theme.css")" media="screen" />
    <link rel="stylesheet" href="@Url.Content("~/assets/css/main.css")" />
    <link rel="stylesheet" href="@Url.Content("~/assets/css/bootstrap-clockpicker.min.css")" />
    <link rel="stylesheet" href="@Url.Content("~/assets/css/prettyPhoto.css")" />
    <script type="text/javascript" src="@Url.Content("https://code.jquery.com/jquery-1.7.2.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/assets/js/bootstrap-clockpicker.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/assets/js/jquery.prettyPhoto.js")"></script>
    <script src="@Url.Content("https://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js")"></script>
    <script src="@Url.Content("~/assets/js/headroom.min.js")"></script>
    <script src="@Url.Content("~/assets/js/custom.js")"></script>
    <script src="@Url.Content("~/assets/js/jQuery.headroom.min.js")"></script>
    <script src="@Url.Content("~/assets/js/template.js")"></script>
    <link href="@Url.Content("https://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/moment.js")"></script>
    <script src="@Url.Content("~/assets/js/fullcalendar.js")"></script>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.3.1/fullcalendar.print.css" media="print" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.3.1/fullcalendar.min.css" />
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="assets/js/html5shiv.js"></script>
    <script src="assets/js/respond.min.js"></script>
    <![endif]-->
    <style>
        .hgt {
            height: 500px;
            min-height: 500px !important;
        }

        .box {
            width: auto;
            border: 4px solid #FFD700;
            box-shadow: inset 0 -1px 0 0 #FFD700, inset 0 1px 0 0 #FFD700, 0 1px 0 0 #FFD700, 0 -1px 0 0 #FFD700;
            height: auto;
            color: #f8d66a !important;
            /* padding: 25px 30px; */
            background: transparent;
            border-radius: 17px;
            margin: 10px !important;
        }
    </style>
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        function GetDay(date) {
            var _day = "";
            var _tu = "@Url.Action("GetDay", "chat")"; 
            $.ajax({
                type: 'POST',
                url: _tu,
                data: { '_date': date },
                async: false,
                success: function (response) {
                    _day = response;
                }
            });
            return _day;
        }
    </script>
</head> 
<body>
    <!-- Fixed navbar -->
    <div class="navbar navbar-inverseCustom navbar-inverse navbar-fixed-top headroom">
        <div class="container">
            <div class="navbar-header">
                <!-- Button for smallest screens -->
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
                <a class="navbar-brand" href="@Url.Action("dashboard","main")"><img class="logoImage" src="@Url.Content("~/assets/images/logo.png")" alt="Califonia SPA"></a>
            </div>
            <div class="navbar-collapse collapse blackgroungblack">
                <ul class="nav navbar-nav pull-right">
                    <li><a href="@Url.Action("dashboard","main")">ClientHome</a></li>
                    <li><a href="@Url.Action("index","therapist")">Therapists Profiles/Book Appt</a></li>
                    <li><a href="@Url.Action("chat","account")">Chat</a></li>
                    <li class="active"><a class="btn" href="@Url.Action("MyAccount","Account")">My Profile</a></li>
                    <li><a href="@Url.Action("logout","Account")">SignOut</a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>
    <!-- /.navbar -->
    <header id="head" class="secondaryCustom"></header>
    <!-- container -->
    <div class="container hgt">
        @RenderBody()
    </div>
    <div class="clearfix"></div>
    <!-- /container -->
    <footer id="footer">
        <hr class="customhr" />
        <table class="col-md-12 col-sm-12 col-lg-12">
            <tbody>
                <tr>
                    <td class="col-md-4 col-sm-4 col-lg-4"></td>
                    <td class="col-md-4 col-sm-4 col-lg-4">
                        <p class="box effect1 text-center box65">
                            <strong>
                                <span class="gspan"> NEED HELP contact Admin  on WhatsApp 9591895700</span>
                            </strong>
                        </p>
                    </td>
                    <td class="col-md-4 col-sm-4 col-lg-4"></td>
                </tr>
            </tbody>
        </table>
    </footer>
    <!-- JavaScript libs are placed at the end of the document so the pages load faster -->

</body>
</html>