californiaspa/Models/Appointment/AppointmentModel.cs
using californiaspa.Models;
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;

namespace californiaspa.Models.Appointment
{
	public class AppointmentModel : ErrorModel
	{
		public List<AppointmentModel_item> appt
		{
			get;
			set;
		}

		public List<AppointmentModel_item> lstPunctualityReports
		{
			get;
			set;
		} 
	}
}

californiaspa/Models/Appointment/AppointmentModel_item.cs
using californiaspa.Models;
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;

namespace californiaspa.Models.Appointment
{
    public class AppointmentModel_item : ErrorModel
    {
        public string address
        {
            get;
            set;
        }

        public string locationurl
        {
            get;
            set;
        }

        public int Aid
        {
            get;
            set;
        }

        public int SpaHotelid
        {
            get;
            set;
        }

        public decimal amount
        {
            get;
            set;
        }

        public List<AppointmentModel_item> appt
        {
            get;
            set;
        }

        public string appTime
        {
            get;
            set;
        }

        public string aptName
        {
            get;
            set;
        }

        public string aptNumber
        {
            get;
            set;
        }

        public string arrivalTime
        {
            get;
            set;
        }

        public int ClientId
        {
            get;
            set;
        }

        public string ClientMobile
        {
            get;
            set;
        }

        public string ClientName
        {
            get;
            set;
        }

        public string ClientPickUptime
        {
            get;
            set;
        }

        public string comments
        {
            get;
            set;
        }

        public string createdDate
        {
            get;
            set;
        }

        public string crossstreetName
        {
            get;
            set;
        }

        public string custommessage
        {
            get;
            set;
        }

        public string finishTime
        {
            get;
            set;
        }

        public string floorNumber
        {
            get;
            set;
        }

        public string hotelName
        {
            get;
            set;
        }

        public string houseNumber
        {
            get;
            set;
        }

        public bool isLeftCabTime
        {
            get;
            set;
        }

        public bool isstartmassage
        {
            get;
            set;
        }

        public string landmark
        {
            get;
            set;
        }

        public string localityArea
        {
            get;
            set;
        }

        public string location
        {
            get;
            set;
        }

        public string ltd
        {
            get;
            set;
        }

        public string lth
        {
            get;
            set;
        }

        public string pickdrop
        {
            get;
            set;
        }

        public string rate
        {
            get;
            set;
        }

        public string roomNumber
        {
            get;
            set;
        }

        public string SpaMap
        {
            get;
            set;
        }

        public string startDate
        {
            get;
            set;
        }

        public string startTime
        {
            get;
            set;
        }

        public string status
        {
            get;
            set;
        }

        public string streetName
        {
            get;
            set;
        }

        public string therapistMobile
        {
            get;
            set;
        }

        public string therapistName
        {
            get;
            set;
        }

        public string therapistTime
        {
            get;
            set;
        }

        public int thid
        {
            get;
            set;
        }

        public string tltd
        {
            get;
            set;
        }

        public int srno
        {
            get;
            set;
        }

        public string tlth
        {
            get;
            set;
        }

        public string token
        {
            get;
            set;
        }

        public string tokenId
        {
            get;
            set;
        }

        public int TotalVaritaion
        {
            get;
            set;
        }

        public string variation
        {
            get;
            set;
        }

        public VehicalModel vehical
        {
            get;
            set;
        }
    }
}

californiaspa/Models/Appointment/VehicalModel.cs
using System;
using System.Runtime.CompilerServices;

namespace californiaspa.Models.Appointment
{
	public class VehicalModel
	{
		public string vcolor
		{
			get;
			set;
		}

		public string vlicenceNumber
		{
			get;
			set;
		}

		public string vmake
		{
			get;
			set;
		}

		public string vmodelNumber
		{
			get;
			set;
		}

		public string vtype
		{
			get;
			set;
		}

		public VehicalModel()
		{
		}
	}
}

californiaspa/Controllers/AppointmentController.cs
using californiaspa.DataBase;
using californiaspa.Models.Appointment;
using californiaspa.utilis;
using System;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace californiaspa.Controllers
{
    public class AppointmentController : Controller
    {
        public string confirm2()
        {
            TimeZoneInfo curTimeZone = TimeZoneInfo.Local;
            return curTimeZone.Id;
        }

        public string getclientterms(int id)
        {
            string str = "";
            string str1 = "<p class='paragraphColor'>1)Booking made under CLIENTS  name by ANIL\v\r\nDO NOT MENTION SPA \r\nJUST SAY ANILS BOOKING</p>\r\n<p class='paragraphColor'>2)Talk to any attendant at reception or to Vishwas \r\nShow him I'd \r\nPAN CARD NOT ACCEPTED DL VOTER I'D ADHAAR OK\r\nBOOKING NAME WITH SPA MUST MATCH ID</p>\r\n <p class='paragraphColor'>3)PAY1000  TO THERAPIST AS PMT HAS ALREADY BEEN MADE TO SERVICE APT IN ADVANCE\r\nDO NOT PAY THEM</p>\r\n<p class='paragraphColor'>4)If\u00a0 the room is dirty contact me.Therapist will come direct to room</p>\r\n<p class='paragraphColor'>3)Stayvel Inn Service Apt\r\nIn same lane as Chalo Punjab Restaurant \r\nOpposite Carrots restaurant \r\nSame lane as Ganapati wines \r\n80ft road \r\nEjipura \r\n2 min from Sony Signal</p>\r\n<p class='paragraphColor'>4)Go to reception \r\nTell them Booking room number\r\nGo to 4th floor sit on chair. Therapist has room key</p>\r\n<p class='paragraphColor'>5)Geyser switch is there for hot water You have to put on 15 min ahead.  Ask therapist  to show you which is geyser switch</p>\r\n<p class='paragraphColor'>\v6)IF YOU ARE LATE THEN MASSAGE TIME WILL BE PROPORTIONATELY REDUCED\r\nBOOKINGS HERE ARE VERY BUSY SO PLEASE COME 15 MIN BEFORE</p>\r\n<p class='paragraphColor'>7)NO ALCOHOL SMOKING DRUGS</p>\r\n<p class='paragraphColor'>8)Towels Soap Shampoo given by Therapist </p>\r\n<p class='paragraphColor'>9)\vRegular water is free Mineral water is rs 25 extra. Make sure the room boy gives change back to you.</p>\r\n<p class='paragraphColor'>10)Any issues with hotel talk to Vishwas</p>";
            string str2 = "<p class='paragraphColor'>1)Go to Front Desk Ask for Sushma if not there say Booking for California SPA Pay rs 1500 including taxes </p>\r\n<p class='paragraphColor'>2)Check in 15 mins early\r\nTalk to Mgr Sushma\r\nShow her  I'd \r\nNO PAN DL ADHAAR OR VOTER ID</p>\r\n<p class='paragraphColor'>3)SHe will chk you into room \r\n1500 ac Whatsapp room number to me Therapist will come direct to room </p>\r\n<p class='paragraphColor'>4)Skyland hotel\r\nSampige rd\r\nNear Al bek restaurant \r\nNear mantri mall \r\nMalleswaram</p>\r\n<p class='paragraphColor'>5)IF YOU ARE MORE THAN 15 MIN LATE THEN MASSAGE TIME WILL BE REDUCED  PROPORTIONATELY </p>\r\n<p class='paragraphColor'>6)Please check if room.and bath are clean,  clean bedsheets,  2 clean towels and 2 soaps and drinking water and glassRegular water is free Mineral water is rs 25 extra. Make sure the room boy gives change back to you. \r\nAny issues with hotel talk to Mgr  Sushma  If still problems whatsapp me</p>\r\n<p class='paragraphColor'>7) NO SMOKING DRUGS ALCOHOL CONDOMS</p>";
            if (id == 4)
            {
                str = str2;
            }
            else if (id == 7 || id == 9)
            {
                str = str1;
            }
            return (new HtmlString(str)).ToString();
        }

        [AuthorizeVerifieduser]
        public ActionResult Getrequest(string token, string name = "C")
        {
            Crypto crypto = new Crypto();
            bookingServices bookingService = new bookingServices();
            token = token.Replace(" ", "+");
            int num = Convert.ToInt32(crypto.DecryptStringAES(token));
            if (name == "C")
            {
                ViewBag.Name = "Confirmed Appointment";
            }
            else
            {
                ViewBag.Name = "Appointment Request";
            }
            return base.View(bookingService.GetAppointMentDetailById(num, false));
        }

        [AuthorizeVerifieduser]
        public ActionResult GetrequestById(int? _xid)
        {
            Crypto crypto = new Crypto();
            bookingServices bookingService = new bookingServices();
            ViewBag.Name = "Confirmed Appointment";
            AppointmentModel_item appointmentModelItem = new AppointmentModel_item();
            appointmentModelItem = bookingService.GetAppointMentDetailById(_xid.Value, false);
            return base.View("Getrequest", appointmentModelItem);
        }

        public string gettherapistterms(int id)
        {
            string str = "";
            string str1 = " <p class='paragraphColor'>1)TAKE 1000  FROM CLIENT AS PMT HAS ALREADY BEEN MADE TO SERVICE APT IN ADVANCE\r\nDO NOT PAY THEM</p>\r\n<p class='paragraphColor'>2)If\u00a0 the room is dirty contact me.</p>\r\n<p class='paragraphColor'>3)Stayvel Inn Service Apt\r\nIn same lane as Chalo Punjab Restaurant \r\nOpposite Carrots restaurant \r\nSame lane as Ganapati wines \r\n80ft road \r\nEjipura \r\n2 min from Sony Signal</p>\r\n<p class='paragraphColor'>4)Geyser switch is there for hot water You have to put on 15 min ahead.</p>\r\n<p class='paragraphColor'>5)If Client is more than 15 min late then reduce time proportionately </p>\r\n<p class='paragraphColor'>6)NO ALCOHOL SMOKING DRUGS</p>\r\n<p class='paragraphColor'>7)Towels Soap Shampoo given by Therapist to Client </p>\r\n<p class='paragraphColor'>8)\vRegular water is free Mineral water is rs 25 extra. Make sure the room boy gives change back to you.</p>\r\n<p class='paragraphColor'>9)Any issues with hotel talk to Vishwas</p>";
            string str2 = "<p class='paragraphColor'>1)Go to Front Desk Ask for Room number under CLIENTS name  If any question say Booking for California SPA </p>\r\n<p class='paragraphColor'>2) If you don't have room number whstsapp Anil</p>\r\n<p class='paragraphColor'>3)Skyland hotel\r\nSampige rd\r\nNear Al bek restaurant \r\nNear mantri mall \r\nMalleswaram</p>\r\n<p class='paragraphColor'>4)IF CLIENT IS MORE THAN 15 MIN LATE THEN MASSAGE TIME WILL BE REDUCED  PROPORTIONATELY </p>\r\n<p class='paragraphColor'>5)Please check if room.and bath are clean,  clean bedsheets,  2 clean towels and 2 soaps and drinking water and glassRegular water is free Mineral water is rs 25 extra. Make sure the room boy gives change back to you. \r\nAny issues with hotel talk to Mgr  Sushma  If still problems whatsapp me</p>\r\n<p class='paragraphColor'>6) NO SMOKING DRUGS ALCOHOL CONDOMS</p>";
            if (id == 4)
            {
                str = str2;
            }
            else if (id == 7 || id == 9)
            {
                str = str1;
            }
            return (new HtmlString(str)).ToString();
        }

        [AuthorizeVerifieduser]
        public ActionResult reject_request(string token)
        {
            int num = Convert.ToInt32((new Crypto()).DecryptStringAES(token));
            Crypto crypto = new Crypto();
            bookingServices bookingService = new bookingServices();
            ViewBag.Name = "Reject Appointment";
            AppointmentModel_item appointmentModelItem = new AppointmentModel_item();
            return base.View("reject_request", bookingService.GetAppointMentDetailById(num, false));
        }

        [AuthorizeVerifieduser]
        public ActionResult request()
        {
            bookingServices bookingService = new bookingServices();
            int num = 0;
            if (Session["Aid"] != null)
            {
                num = Convert.ToInt32(Session["Aid"].ToString());
                Session["Aid"] = null;
            }
            return base.View(bookingService.GetAppointMentDetailById(num, false));
        }

        [AuthorizeVerifieduser]
        public ActionResult sendRequest(string token)
        {
           
            string str = token;
            Crypto crypto = new Crypto();
            bookingServices bookingService = new bookingServices();
            str = str.Replace(" ", "+");
            Task.Factory.StartNew(() => bookingService.SendAppointmentRequest(Convert.ToInt32(crypto.DecryptStringAES(str))));
            TempData["mesg"] = "check home page chat  for messages from therapist  You can communicate with therapist through web";
            return base.RedirectToAction("index", "therapist");
        }
    }
}

californiaspa/Views/Appointment/GetrequestById.cshtml
@{
    ViewBag.Title = "GetrequestById";
    Layout = "~/Views/Shared/_Layoutuser.cshtml";
}

<h2>GetrequestById</h2>

californiaspa/Views/Appointment/confirm.cshtml
@{
    ViewBag.Title = "confirm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">

    <!-- Article main content -->
    <article class="col-xs-12 maincontent">
        <header class="page-header">
            <h1 class="page-title">Appointment Confirm</h1>
        </header>

        <div class="col-md-8 col-md-offset-1 col-sm-8 col-sm-offset-1">
            <div class="panel panel-default">
                <div class="panel-body">


                    <form>
                        <div class="top-margin">
                            <label>Name of therapist :</label>
                            <span>Umesh Kamboj</span>
                        </div>
                        <div class="top-margin">
                            <label>Date :</label>
                            <span>24-feb-1990</span>
                        </div>
                        <div class="top-margin">
                            <label>Start time :</label>
                            <span>06:26 PM</span>
                        </div>

                        <div class="top-margin">
                            <label>Start location:</label>
                            <span># 353 street - calfornia 1</span>
                        </div>
                        <div class="top-margin">
                            <label>Arrival time :</label>
                            <span>06:26 PM</span>
                        </div>
                        <div class="top-margin">
                            <label>Address :</label>
                            <span># 353 street - calfornia 1</span>
                        </div>
                        <div class="top-margin">
                            <label>Amount :</label>
                            <span>20$</span>
                        </div>
                        <div class="top-margin">
                            <label>pick and drop or transport  :</label>
                            <span>transport</span>
                        </div>
                        <div class="top-margin">
                            <label>Custom Message  :</label>
                            <span> Hello how are you , I want to meet you with this new example , with demo class in this demo class</span>
                        </div>


                        <hr>
                        <div class="row">
                            <div class="col-lg-3">
                                <span> Please review all detail including start time</span>
                            </div>
                            <div class="col-lg-9 text-right">
                                <button class="btn btn-action" type="submit"> Edit </button>
                                <button class="btn btn-action" type="submit">Confirm Request</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </article>
    <!-- /Article -->

</div>

californiaspa/Views/Appointment/request.cshtml
@{
    ViewBag.Title = "Request";
    Layout = "~/Views/Shared/_Layoutuser.cshtml";
}
@model californiaspa.Models.Appointment.AppointmentModel_item

@helper FormatDate(string date)
{
var d = Convert.ToDateTime(date);
    <span>@d.ToString("d-MMM-y")</span>
}
@helper FormatDateWithTime(string date)
{
var d = Convert.ToDateTime(date);
    <span>@d.ToString("d-MMM-y ; hh:mm tt")</span>
}
@helper FormatDay(string date)
{
var d = Convert.ToDateTime(date);
    <span>@d.DayOfWeek</span>
}
<style>
    iframe {
        display: block;
        width: 100%;
    }
</style>

<script>
    function initMap() {
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(function (p) {
                var LatLng = new google.maps.LatLng(p.coords.latitude, p.coords.longitude);
                var mapOptions = {
                    center: LatLng,
                    zoom: 12,
                    mapTypeId: google.maps.MapTypeId.ROADMAP,
                    gestureHandling: 'greedy',
                    disableDefaultUI: true
                };

                var map = new google.maps.Map(document.getElementById("map2"), mapOptions);
                var marker = new google.maps.Marker({
                    animation: google.maps.Animation.BOUNCE,
                    position: LatLng,
                    map: map,
                    title: "<div><b>Your location:</b><br />Latitude: " + p.coords.latitude + "<br />Longitude: " + p.coords.longitude
                });

                var pos = {
                    lat: p.coords.latitude,
                    lng: p.coords.longitude
                };
                google.maps.event.addListener(marker, "click", function (e) {
                    var infoWindow = new google.maps.InfoWindow();
                    infoWindow.setContent(marker.title);
                    infoWindow.open(map, marker);
                    infoWindow.setPosition(pos);
                    map.setCenter(pos);
                });

            });

        } else {
            alert('Geo Location feature is not supported in this browser.');
        }
    }
    function initMap1(lat, lth, id) {
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(function (p) {
                var LatLng = new google.maps.LatLng(lat, lth);
                var mapOptions = {
                    center: LatLng,
                    zoom: 12,
                    gestureHandling: 'greedy',
                    mapTypeId: google.maps.MapTypeId.ROADMAP,
                    disableDefaultUI: true
                };

                var map = new google.maps.Map(document.getElementById(id), mapOptions);
                var marker = new google.maps.Marker({
                    animation: google.maps.Animation.BOUNCE,
                    position: LatLng,
                    map: map,
                    title: "<div><b>Your location:</b><br />Latitude: " + p.coords.latitude + "<br />Longitude: " + p.coords.longitude
                });

                var pos = {
                    lat: p.coords.latitude,
                    lng: p.coords.longitude
                };
                google.maps.event.addListener(marker, "click", function (e) {
                    var infoWindow = new google.maps.InfoWindow();
                    infoWindow.setContent(marker.title);
                    infoWindow.open(map, marker);
                    infoWindow.setPosition(pos);
                    map.setCenter(pos);
                });
            });

        } else {
            alert('Geo Location feature is not supported in this browser.');
        }
    }

</script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDwLSy7V_ejK6m-ffhI6kiiJf3wl7pnX2g&callback=initMap">
</script>
<div class="row">
    <article class="col-xs-12 maincontent">
        <header class="page-header">
            <h4>
                Review Appointment Request
                <a class="btn btn-action pull-right" href="@Url.Action("index","booking",new {token=Model.token,tokenId=Model.tokenId })"> Return to booking </a>
            </h4>
            <div id="map2" class="notDisplay"></div>
        </header>
        <div class="col-md-8 col-md-offset-1 col-sm-8 col-sm-offset-1">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="top-margin">
                        <label>Client Initiated Booking On Date / Time :</label>
                        <span>@FormatDateWithTime(Model.createdDate) (@FormatDay(Model.createdDate))</span>
                        <br />
                        <span>This is NOT Appointment date Time</span>
                    </div>
                    <div class="top-margin">
                        <label>Name of therapist :</label>
                        <span>@Model.therapistName</span>
                    </div>
                    <div class="top-margin">
                        <label>Massage Appointment Date:</label>
                        <span>@FormatDate(Model.startDate) (@FormatDay(Model.startDate))</span><br />
                        <span>This is the date you actually want the massage appointment</span>
                    </div>
                    <div class="top-margin">
                        <label>Client Requested Earliest START time:</label>
                        <span>@Model.startTime</span>
                    </div>

                    <div class="top-margin">
                        <label>Client Requested Latest START time : </label>
                        <span>@Model.arrivalTime</span>
                    </div>
                    <div class="top-margin">
                        <span>Therapist to confirm a time between the above or enter a different time</span>
                    </div>

                    <div class="top-margin">
                        <label> location:</label>
                        <span>@Model.location</span>
                    </div>

                    <div class="top-margin">
                        <label>Address :</label>
                        <span>@Model.address</span>
                    </div>
                    @if (!string.IsNullOrEmpty(Model.houseNumber))
                    {
                        <div class="top-margin">
                            <label>House Number :</label>
                            <span>@Model.houseNumber</span>
                        </div>
                    }
                    @if (!string.IsNullOrEmpty(Model.aptNumber))
                    {
                        <div class="top-margin">
                            <label>Flat Number :</label>
                            <span>@Model.aptNumber</span>
                        </div>
                    }
                    @if (!string.IsNullOrEmpty(Model.hotelName))
                    {
                        <div class="top-margin">
                            <label>Hotel Name :</label>
                            <span>@Model.hotelName</span>
                        </div>
                    }
                    @if (!string.IsNullOrEmpty(Model.floorNumber))
                    {
                        <div class="top-margin">
                            <label>Floor Number :</label>
                            <span>@Model.floorNumber</span>
                        </div>
                    }
                    @if (!string.IsNullOrEmpty(Model.roomNumber))
                    {
                        <div class="top-margin">
                            <label>Room Number :</label>
                            <span>@Model.roomNumber</span>
                        </div>
                    }
                    @if (!string.IsNullOrEmpty(Model.aptName))
                    {
                        <div class="top-margin">
                            <label>Apt. Name :</label>
                            <span>@Model.aptName</span>
                        </div>
                    }
                    @if (!string.IsNullOrEmpty(Model.streetName))
                    {
                        <div class="top-margin">
                            <label>Street Name :</label>
                            <span>@Model.streetName</span>
                        </div>
                    }
                    @if (!string.IsNullOrEmpty(Model.crossstreetName))
                    {
                        <div class="top-margin">
                            <label>Cross Street Name :</label>
                            <span>@Model.crossstreetName</span>
                        </div>
                    }
                    @if (!string.IsNullOrEmpty(Model.landmark))
                    {
                        <div class="top-margin">
                            <label>LandMark :</label>
                            <span>@Model.landmark</span>
                        </div>
                    }
                    @if (!string.IsNullOrEmpty(Model.localityArea))
                    {
                        <div class="top-margin">
                            <label>Locality Area :</label>
                            <span>@Model.localityArea</span>
                        </div>
                    }

                    <div class="top-margin">
                        <label>Amount :</label>
                        <span>Rs &nbsp;@Model.rate </span>
                    </div>
                    <div class="top-margin">
                        <label>pick and drop or transport  :</label>
                        <span>@Model.pickdrop</span>
                    </div>
                    @if (!string.IsNullOrEmpty(Model.ClientPickUptime))
                    {
                        <div class="top-margin">
                            <label>Client Pick-up Time  :</label>
                            <span>@Model.ClientPickUptime</span>
                        </div>
                    }
                    @if (!string.IsNullOrEmpty(Model.vehical.vcolor))
                    {
                        <div class="top-margin">
                            <label>Vehical color  :</label>
                            <span>@(Model.vehical.vcolor)</span>
                        </div>
                    }
                    @if (!string.IsNullOrEmpty(Model.vehical.vlicenceNumber))
                    {
                        <div class="top-margin">
                            <label>License Number  :</label>
                            <span>@(Model.vehical.vlicenceNumber)</span>
                        </div>
                    }
                    @if (!string.IsNullOrEmpty(Model.vehical.vmake))
                    {
                        <div class="top-margin">
                            <label>Make  :</label>
                            <span>@(Model.vehical.vmake)</span>
                        </div>
                    }
                    @if (!string.IsNullOrEmpty(Model.vehical.vmodelNumber))
                    {
                        <div class="top-margin">
                            <label>Model Number  :</label>
                            <span>@(Model.vehical.vmodelNumber)</span>
                        </div>
                    }
                    @if (!string.IsNullOrEmpty(Model.vehical.vtype))
                    {
                        <div class="top-margin">
                            <label>Bike Or Car :</label>
                            <span>@(Model.vehical.vtype)</span>
                        </div>
                    }
                    <div class="top-margin">
                        <label>Custom Message  :</label>
                        <span> @Model.custommessage</span>
                    </div>
                    @if (Model.ltd != "0" && string.IsNullOrEmpty(Model.SpaMap))
                    {
                        <div class="top-margin">
                            <label>Check Appointment Location  :</label>
                            <div id="Map" class="mapDiv"> </div>
                            <span>Please check if house address given matches map location.To enlarge map use 2 fingers and to move use 1 finger </span>
                            <script>
                                initMap1('@Model.ltd', '@Model.lth', 'Map');
                            </script>
                        </div>
                    }
                    else
                    {
                        <div class="top-margin">
                            <label>Check Appointment Location  :</label>
                            <div class="mapDiv">
                                @Html.Raw(Model.SpaMap)
                            </div>
                        </div>
                    }
                    <div class="top-margin">
                        <span>Check your messages from therapist by going to home and chat screen. Confirmation will be sent sms. If you don't get reply within 30 min whstsapp to manager</span>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-lg-9 text-right">
                            <a class="btn btn-action" href="@Url.Action("index","booking",new {token=Model.token,tokenId=Model.tokenId })"> Edit </a>
                            <a class="btn btn-action" href="@Url.Action("sendRequest","Appointment",new {token=Model.tokenId})">Send Request to Therapist</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </article>
</div>